version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-nvm-{{ checksum ".nvmrc" }}
            # fallback to using the latest cache if no exact match is found
            - v1-nvm-
      - run:
          name: Install node via .nvmrc
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            nvm use
            nvm alias default $(cat .nvmrc)

            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - save_cache:
          paths:
            - /opt/circleci/.nvm
          key: v1-nvm-{{ checksum ".nvmrc" }}
      - run:
          name: install pnpm
          command: npm install -g pnpm
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pnpm-lock.yaml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install
          command: NODE_ENV=development pnpm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "pnpm-lock.yaml" }}
      # clean
      - run: docker network prune --force
      - run: npx commitlint-circle
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run test
      - run:
          name: release
          command: npm run semantic-release || true
